### PR TITLE
Miscellany

### PR DESCRIPTION
**Pull request by bgamari**
Add details to readme, ignore `_shake` directory.

### CODE REVIEW

**Comment by bgamari** [comment]
This ought to fix #6.

**Comment by snowleopard** [comment]
Regarding 77d34c7:

Have a look at this commit: ddfe5bc. I decided to move the shake database inside `shake-build` and renamed it to `.db`. To make naming consistent I also renamed `_shake` to `.shake` (this also matches the naming convention for `.git` and `.arc-linters`. If you agree with this naming convention please amend 77d34c7.

**Comment by snowleopard** [comment]
Regarding 576a06c:

I think this will become redundant once #5 is fixed. The `build` action already depends on the corresponding builder, so once I relocate all binaries to `inplace/bin` they will automatically be tracked.

**Comment by bgamari** [comment]
Ahh, I see. Alright, perhaps I'll drop the `gitignore` change and "Documentation: Depend upon haddock for stage".

**Comment by bgamari** [comment]
@snowleopard I think this is ready for another review.

**Comment by snowleopard** [comment]
Excellent! This is now merged. I'll now look into #6.

**Pull request merged**
