### PR TITLE
fix handling of --with-gmp-* configure arguments

### PR DESCRIPTION
**Pull request by kgardas**
This fixes part of issue #159.

### CODE REVIEW

**Comment by snowleopard** [comment]
Many thanks @kgardas!

I have a question about this piece of code:
```haskell
configMk <- liftIO . readFile $ gmpBase -/- "config.mk"
if "HaveFrameworkGMP = YES" `isInfixOf` configMk
then do
    putBuild "| GMP framework detected and will be used"
    copyFile gmpLibraryFakeH gmpLibraryH
else if "HaveLibGmp = YES" `isInfixOf` configMk
     then do
       putBuild "| GMP detected and will be used"
       copyFile gmpLibraryFakeH gmpLibraryH
     else do [...]
```
It looks like the first two checks can be combined into one:
```haskell
configMk <- liftIO . readFile $ gmpBase -/- "config.mk"
if "HaveFrameworkGMP = YES" `isInfixOf` configMk || "HaveLibGmp = YES" `isInfixOf` configMk
then do
    putBuild "| GMP framework detected and will be used"
    copyFile gmpLibraryFakeH gmpLibraryH
else do [...]
```
Do you know if these two checks should indeed be handled in the same way? If yes, perhaps you can merge them as above to simplify the code.

Which of the two checks is activated on your machine? I presume the one with `HaveLibGmp`.

**Comment by kgardas** [comment]
@snowleopard yes, checks can be combined, but then for initial testing I kept this in a way to see the difference in detection of frameworks-based or plain GMP. Honestly "framework GMP" is IIRC Mac OS X specific thing.
And yes, you are right on Solaris and everywhere else except probably Mac OS X, HaveLibGmp is YES when the GMP library is detected.
OK! Will merge the checks now...

**Comment by snowleopard** [comment]
> I kept this in a way to see the difference in detection of frameworks-based or plain GMP

Another question (sorry, I have very little understanding of GMP): what is the difference between "plain" and "framework-based" GMP?

**Comment by ndmitchell** [comment]
My rough understanding is that Mac is too cool to use libraries like everyone else, so they use frameworks, which I've always viewed as an alternative to a set of dll/so but with more metadata. See http://stackoverflow.com/questions/4618027/what-exactly-is-a-framework-in-mac-os-x-framework-folders.

**Comment by kgardas** [comment]
@snowleopard don't know any information about framework GMP except that the term is used in GHC and the check is done in a different way, see the code in libraries/integer-gmp/aclocal.m4:
```
AC_DEFUN([LOOK_FOR_GMP_FRAMEWORK],[
    if test "$HaveLibGmp" = "NO"
    then
        case $target_os in
        darwin*)
            AC_MSG_CHECKING([for GMP.framework])
            save_libs="$LIBS"
            LIBS="-framework GMP"
            AC_TRY_LINK_FUNC(__gmpz_powm_sec,
                             [HaveFrameworkGMP=YES; GMP_FRAMEWORK=GMP])
            LIBS="$save_libs"
            AC_MSG_RESULT([$HaveFrameworkGMP])
            ;;
        esac
    fi
```
and in configure.ac in the same dir:
```
AC_ARG_WITH([gmp-framework-preferred],
  [AC_HELP_STRING([--with-gmp-framework-preferred],
    [on OSX, prefer the GMP framework to the gmp lib])],
    [GMP_PREFER_FRAMEWORK=YES],
    [GMP_PREFER_FRAMEWORK=NO])
```
looks like pure Mac-ism...

**Comment by kgardas** [comment]
@ggreif silly me, indeed map is working also on empty lists. @snowleopard I'll provide simplified version based on @ggreif code...

**Comment by snowleopard** [comment]
Many thanks all! Looking forward to the last revision, ready to merge.

**Comment by snowleopard** [comment]
Let me hold on with the merge while I'm checking how to fix the Travis regression which happens when GMP is already installed. I wonder why @kgardas hasn't experienced the same error...

**Comment by kgardas** [comment]
@snoleopard the build fails when gmp is installed/detected and fails with:
```
Error when running Shake build system:
* utils/compare_sizes/stage1/build/tmp/compareSizes
* .build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.1.a
* getDirectoryFiles  [.build/stage0/gmp/objs/*.o]
.build/stage0/gmp/objs: getDirectoryContents: does not exist (No such file or directory)
```
that probably means that some from the infrastructure still counts with the object file from in tree built GMP and would like to do something with it.

**Comment by ndmitchell** [comment]
So seems @kgardas is hit by this bug. It's a Shake bug :( Workaround is to `doesDirectoryExist` first, which is deeply sad, as I previously told @snowleopard it definitely wasn't required (and thus my beer count increases further).

**Comment by snowleopard** [comment]
Let me merge this and temporary fix the bug with an extra `doesDirectoryExist` check.

**Comment by snowleopard** [comment]
With the above fix we no longer have the `getDirectoryContents` error. However, on my machine I get a linking error when using installed GMP. Will investigate now.

**Comment by snowleopard** [comment]
I found the following comment in the old build system:
```
# Apparently building on Windows fails when there is a system gmp
# available, so we never try to use the system gmp on Windows
```
I think we can mirror the old build system here. Maybe we will come back to fixing system GMP on Windows in future.

**Comment by snowleopard** [comment]
Done.

**Pull request merged**
