### PR TITLE
Travis CI using dirty tricks

### PR DESCRIPTION
**Pull request by quchen**
A rather hacky way to get CI going.

The problem is that Travis clones into a certain directory, but we'd like the Shake build system to be part of a second clone we have to do explicitly (GHC). The script does some dirty tricks to get it done™, but we should probably clean up the attempt a bit in the future.

CI build log: https://travis-ci.org/quchen/shaking-up-ghc

### CODE REVIEW

**Comment by snowleopard** [comment]
Cool, thanks! Let's try.

**Comment by snowleopard** [comment]
It currently says "This is not an active repository": https://travis-ci.org/snowleopard/shaking-up-ghc

Do I have to do anything to activate it?

**Comment by quchen** [comment]
@snowleopard Yes, you need to activate Travis. To do that, go to the Github repo -> (Project) Settings ->Webhooks & Services -> Add Service -> Travis CI -> Confirm. Your Github Repo now sends notices to Travis on each push. Now you need to let Travis know that you'd actually like to build the repo; for that, login on Travis-CI.org, go to the top right where your name is, click on it, then on Accounts. You should see a list of your projects; activate the one for GHC-Shake, and you should be good to go.

**Comment by snowleopard** [comment]
@quchen Many thanks! I think it worked. At least the page is now alive: https://travis-ci.org/snowleopard/shaking-up-ghc.

**Comment by snowleopard** [comment]
Right. Travis build failed at the very start:
```
Error when running Shake build system:
* OracleQ (ConfigKey "host-os")
* shake-build/cfg/system.config
Error, file does not exist and no rule available:
  shake-build/cfg/system.config
```
I believe the reason is the missing `./configure` step which produces `system.config` from `system.config.in`. Most likely `./boot` is missing too.

**Comment by snowleopard** [comment]
OK, I attempted this: b978e17. Let's see if it works.

**Pull request merged**
