### PR TITLE
[WIP] Add Travis configuration

### PR DESCRIPTION
**Pull request by bgamari**
This is an attempt at resolving #43.

### CODE REVIEW

**Comment by snowleopard** [comment]
Many thanks. Let me know when it's ready for merge. 

I think it may be worth running a full `make` build before `./shake-build/build.sh`. Otherwise we are long way of seeing the build succeed.

**Comment by angerman** [comment]
I'm in favor of omitting `make`, so that issues surface immediately and are not shadowed by prior `make` runs.
@bgamari can we run CI on Mac or Windows as well with Travis?

**Comment by snowleopard** [comment]
Is it possible to have two different instances of Travis? There are benefits to both `from-the-scratch` and `from-make` builds.

**Comment by bgamari** [comment]
Instead of doing a full `make` why don't we simply enumerate precisely which targets need to be built? Not only will this keep the build time down, but it also gives us a check-list for which functionality remains unimplemented.

**Comment by angerman** [comment]
@bgamari :+1: I just never got the make system to only build certain targets, it always went ahead and built everything (or that's like how it felt).

**Comment by snowleopard** [comment]
@bgamari Sounds good! Some targets are very close to the full build (e.g. the `ghc` package), but many are really small almost independent ones.

**Comment by quchen** [comment]
I think this is now obsolete due to #93. @bgamari

**Comment by snowleopard** [comment]
Thanks @bgamari and @quchen! I'll close this.

**Pull request closed without merging**
