### PR TITLE
Ensure that if ghc compilation fails then we return a non-zero error code from build.bat

### PR DESCRIPTION
**Pull request by ndmitchell**
At the moment if compiling the build script fails the build.bat returns 0, it should return 1 to indicate failure. I checked it still returns 0 on success and 1 on compilation failure.

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks! Not sure what happened with Travis though... but for some reason `build.sh` appears broken?

**Comment by ndmitchell** [comment]
No idea - this patch only touches build.bat. There is a merge commit in there, but the merge doesn't touch build.sh either. Perhaps take the diff from this patch and apply it by hand?

**Comment by ndmitchell** [comment]
And also perhaps rerun the last Travis state? See if the broken sh is somewhere weird, like a Travis version upgrade (I've been bit by those at various points).

**Comment by snowleopard** [comment]
So, it seems to have gone through on AppVeyor, so let me merge this. I'll fix the Travis issue later.

**Comment by snowleopard** [comment]
So, the Travis issue got fixed by itself. So I guess it was Travis fault.

**Pull request merged**
