### PR TITLE
Show Shake statistics, refactor direct Linux build script

### PR DESCRIPTION
**Pull request by quchen**
- Make use of Shake's nice progress report and final statistics
- Lots of quotes for `build.sh`, bash safemode, nice indentation

### CODE REVIEW

**Comment by bgamari** [comment]
Looks good to me. Thanks for cleaning up the build script.

**Comment by snowleopard** [comment]
David, Ben, you are awesome, many thanks! I'll look into all pull requests later today.

**Comment by snowleopard** [comment]
This is now merged. I'll try to transfer some of the improvements into the Windows build script.

**Comment by snowleopard** [comment]
Done: 5bb30bc.

**Pull request merged**
