### PR TITLE
Adds osx to the list of operatin systems in the travis.yml

### LINKED ISSUE #111: CI: Mac
Travis allows to run on their os x infrastructure as well. See https://docs.travis-ci.com/user/workers/os-x-infrastructure/

### PR DESCRIPTION
**Pull request by angerman**
This should fix #111.

### CODE REVIEW

**Comment by angerman** [comment]
This is *acturally* **correct**. The current head **is** broken on `os x`. See #114.

**Comment by angerman** [comment]
Therefore, I consider this ready.

**Comment by angerman** [comment]
travis dies with
```
[mshakeArgsWith                          0.000s    0%                           
Function shake                         0.028s    0%                           
Database read                          0.007s    0%                           
With database                          0.000s    0%                           
Running rules                       3114.325s   99%  =========================
Pool finished (25298 threads, 16 max)  0.000s    0%                           
Lint checking                          0.093s    0%                           
Total                               3114.453s  100%                           
[31mLint checking error - value has changed since being depended upon:
  Key:  doesDirectoryExist libraries/ghc-prim/stage1/build/autogen/GHC/
  Old:  False
  New:  True
```
for the linux build.

**Comment by snowleopard** [comment]
:+1:

**Pull request merged**
